# Generated by Django 5.2.11 on 2026-03-21 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, default='fas fa-folder', max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='颜色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '书签分类',
                'verbose_name_plural': '书签分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(verbose_name='网址')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('favicon', models.URLField(blank=True, verbose_name='图标')),
                ('is_private', models.BooleanField(default=True, verbose_name='隐私')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('source_type', models.CharField(default='manual', max_length=20, verbose_name='来源类型')),
                ('visit_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('last_visited', models.DateTimeField(blank=True, null=True, verbose_name='最后访问')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '书签',
                'verbose_name_plural': '书签',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
