# Generated by Django 6.0.1 on 2026-02-01 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='来源名称')),
                ('source_type', models.CharField(choices=[('api', 'API'), ('rss', 'RSS'), ('manual', '手动')], default='api', max_length=20, verbose_name='来源类型')),
                ('api_url', models.URLField(blank=True, verbose_name='API 地址')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API 密钥')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_sources', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '新闻来源',
                'verbose_name_plural': '新闻来源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('link', models.URLField(verbose_name='原文链接')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('image_url', models.URLField(blank=True, verbose_name='图片')),
                ('published_at', models.DateTimeField(verbose_name='发布时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('is_starred', models.BooleanField(default=False, verbose_name='收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.newssource', verbose_name='来源')),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_categories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '新闻分类',
                'verbose_name_plural': '新闻分类',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
