# Generated by Django 5.2.11 on 2026-03-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_read_later',
            field=models.BooleanField(default=False, verbose_name='稍后阅读'),
        ),
    ]
