# Generated by Django 5.2.11 on 2026-03-30 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('read', '阅读'), ('write', '写作'), ('task_done', '任务完成'), ('bookmark', '收藏书签')], max_length=20)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'activity_type', 'date'], name='core_activi_user_id_36beb0_idx')],
                'unique_together': {('user', 'activity_type', 'date')},
            },
        ),
    ]
