# Generated by Django 5.2.11 on 2026-03-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='是否重复'),
        ),
        migrations.AddField(
            model_name='todo',
            name='last_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次完成时间'),
        ),
        migrations.AddField(
            model_name='todo',
            name='next_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次到期时间'),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence_rule',
            field=models.JSONField(blank=True, null=True, verbose_name='自定义重复规则'),
        ),
        migrations.AddField(
            model_name='todo',
            name='recurrence_type',
            field=models.CharField(choices=[('none', '不重复'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('weekdays', '每个工作日')], default='none', max_length=20, verbose_name='重复类型'),
        ),
    ]
