# Generated by Django 6.0.1 on 2026-02-01 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        ('rss', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWritingPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('prompt_type', models.CharField(choices=[('summary', '文章摘要'), ('rewrite', '改写'), ('expand', '扩写'), ('translate', '翻译'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='提示词类型')),
                ('prompt_template', models.TextField(verbose_name='提示词模板')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI 写作提示词',
                'verbose_name_plural': 'AI 写作提示词',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('note_type', models.CharField(choices=[('text', '文本'), ('markdown', 'Markdown'), ('ai', 'AI 生成')], default='markdown', max_length=20, verbose_name='笔记类型')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_archived', models.BooleanField(default=False, verbose_name='归档')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='news.newsarticle', verbose_name='关联文章')),
                ('related_rss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='rss.rssarticle', verbose_name='关联 RSS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIWritingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='使用的提示词')),
                ('input_content', models.TextField(verbose_name='输入内容')),
                ('output_content', models.TextField(verbose_name='输出内容')),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='AI 模型')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='使用令牌数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_writing_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_history', to='notes.note', verbose_name='笔记')),
            ],
            options={
                'verbose_name': 'AI 写作历史',
                'verbose_name_plural': 'AI 写作历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
