# Generated by Django 5.2.11 on 2026-03-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(blank=True, help_text='可用于登录的唯一别名', max_length=50, null=True, unique=True, verbose_name='别名'),
        ),
    ]
