# Generated by Django 6.0.1 on 2026-02-01 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(verbose_name='RSS 链接')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('favicon', models.URLField(blank=True, verbose_name='图标')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('last_fetched', models.DateTimeField(blank=True, null=True, verbose_name='最后获取时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_feeds', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RSS 订阅源',
                'verbose_name_plural': 'RSS 订阅源',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'url')},
            },
        ),
        migrations.CreateModel(
            name='RSSArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('link', models.URLField(verbose_name='原文链接')),
                ('description', models.TextField(blank=True, verbose_name='摘要')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('published_at', models.DateTimeField(verbose_name='发布时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('is_starred', models.BooleanField(default=False, verbose_name='收藏')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='rss.rssfeed', verbose_name='订阅源')),
            ],
            options={
                'verbose_name': 'RSS 文章',
                'verbose_name_plural': 'RSS 文章',
                'ordering': ['-published_at'],
                'unique_together': {('feed', 'link')},
            },
        ),
    ]
